sudo: required
services:
 - docker

before_install:
 - docker build -t cmotta2016/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run cmotta2016/react-test npm run test -- --coverage

after_success:
 - docker build -t cmotta2016/multi-client ./client
 - docker build -t cmotta2016/multi-nginx ./nginx
 - docker build -t cmotta2016/multi-server ./server
 - docker build -t cmotta2016/multi-worker ./worker
# Log in to the docker CLI
# Configurar no Travis > More Options > Settings > Environment DOCKER_ID e DOCKER_PASSWORD
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
 - docker push cmotta2016/multi-client
 - docker push cmotta2016/multi-nginx
 - docker push cmotta2016/multi-server
 - docker push cmotta2016/multi-worker
